server:
  port: 8087

spring:
  application:
    name: NotificationService
  mail:
    host: smtp.gmail.com
    port: 587
    username: carnivry2022@gmail.com
    password: byxqowufgtlginxh
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.gmail.com
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true