package com.stackroute.model;

public enum Genre {
    MUSIC, SPORTS, COMEDY,DRAMA,CEREMONY,THRILLER, EDUCATION, ADVENTURE, RELIGION, MOVIE, GAMES, ART, HEALTH_N_FITNESS,
    BUSINESS, TECHNOLOGY, LITERATURE, ASTROLOGY, KIDS, DANCE, FOOD, SOCIAL, SEMINAR,SPIRITUAL, MISCELLANEOUS
}
