
server:
  port: 8085

social:
  auto-signup: false



spring:
  application:
    name: RegistrationService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Carnivry
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: carnivry2022@gmail.com
#    password: Carnivry@2022
    password: byxqowufgtlginxh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1023149345964-e17epiqvfhgfcgbnh0dfu1u432r5p2kl.apps.googleusercontent.com
            clientSecret: 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

            redirectUri: http://localhost:4200/registration/callback
#            redirectUri: https://carnivry.stackroute.io/registration/callback
          github:
            clientId: 12880111cd52b9208c9c
            clientSecret: a9f1059fdd7c6ddc648b659ad2a9ce42cdf057ed
            redirectUri: http://localhost:4200/registration/callback
#            redirectUri: https://carnivry.stackroute.io/registration/callback


#  twilio:
#    account_sid: AC8db671d7b95d76cf3c965ddece0135e1
#    auth_token: a1f5709d19e1c8b4211152c32a2330f78
#    trial_number: +18507893794

#eureka:
#  client:
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true

