
server:
  port: 8080

social:
  auto-signup: false

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Carnivry
  mail:
    host: smtp.gmail.com
    port: 587
    username: saumasischandra987@gmail.com
    password: byprdafsjqjyipcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 519435446247-i2orlv7mqvvivg8pucji77t540qahjaa.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:4200/callback
          github:
            clientId: a13359fa2e6525d92711
            clientSecret: 0032ca8c168aac879a0cdef989cccf3681520974
            redirectUri: http://localhost:4200/callback
