spring:
  application:
    name: RegistrationService
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: carnivry2022@gmail.com
    password: byxqowufgtlginxh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1023149345964-e17epiqvfhgfcgbnh0dfu1u432r5p2kl.apps.googleusercontent.com
            clientSecret: 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
            #            redirectUri: https://carnivry.stackroute.io/registration/callback
            redirectUri: https://localhost:4200/#/registration/callback
          github:
            clientId: 12880111cd52b9208c9c
            clientSecret: a9f1059fdd7c6ddc648b659ad2a9ce42cdf057ed
            #            redirectUri: https://carnivry.stackroute.io/registration/
            redirectUri: https://localhost:4200/#/registration/callback
  profiles:
    active: dev
  config:
    import: "configserver:"