package com.stackroute.model;

public enum Genre {
    MUSIC, SPORTS, COMEDY, EDUCATION, ADVENTURE, RELIGION, MOVIE, GAMES, ART, HEALTH_N_FITNESS,
    BUSINESS, TECHNOLOGY, LITERATURE, ASTROLOGY, KIDS, DANCE, FOOD, SOCIAL, MISCELLANEOUS
}
