server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maitymayukh23/soulmate-config-repo
          repos:
            notification-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: NotificationService
              search-paths:
                - configs-location
            authentication-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: AuthenticationService
              search-paths:
                - configs-location
            payment-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: PaymentService
              search-paths:
                - configs-location
            suggestion-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: SuggestionService
              search-paths:
                - configs-location
            ticketing-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: TicketingService
              search-paths:
                - configs-location
            management-properties-repo:
              uri: https://github.com/ProjectCarnivry/config-server-repo
              pattern: ManagementService
              search-paths:
                - configs-location

            registration-properties-repos:
              pattern : RegistrationService
              uri: https://github.com/ProjectCarnivry/config-server-repo
              search-paths:
                 - configs-location


